FROM bitnami/spark:3.5.4

USER root

RUN install_packages \
    fontconfig \
    fonts-nanum \
    libfreetype6 \
    libpng16-16 \
    libjpeg62-turbo \
    ca-certificates && \
    fc-cache -fv && update-ca-certificates

COPY ./news-batch/requirements.spark.txt /tmp/requirements-spark.txt
RUN pip install --no-cache-dir -r /tmp/requirements-spark.txt && rm -f /tmp/requirements-spark.txt

USER 1001
