FROM python:3.10-slim

WORKDIR /opt/news-pipeline

COPY ../news-pipeline/producer/requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir -r ./requirements.txt

COPY ../news-pipeline/producer ./producer
