x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: ./docker/Dockerfile.airflow
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres-news/news
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:postgres@postgres-news/news
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/airflow/data
    - ${AIRFLOW_PROJ_DIR:-.}/batch.env:/opt/airflow/.env:ro
    - ./logs/airflow:/opt/airflow/custom/airflow.log
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres-news:
      condition: service_healthy
  networks:
    - airflow

services:
  postgres-news:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgre
    container_name: postgres-news
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: news
    ports:
      - "5434:5432"
    volumes:
      - news-db-volume:/var/lib/postgresql/data
      - ./sql/init_news_schema.sql:/docker-entrypoint-initdb.d/init_news_schema.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "news"]
      interval: 30s
      retries: 10
      start_period: 60s
      timeout: 20s
    restart: always
    networks:
      - airflow

  redis:
    image: redis:7.2-bookworm
    container_name: airflow-redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    networks:
      - airflow

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    container_name: airflow-init
    command:
      - -c
      - |
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources

  airflow-cli:
    <<: *airflow-common
    container_name: airflow-cli
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow

  flower:
    <<: *airflow-common
    container_name: airflow-flower
    command: celery flower
    profiles:
      - flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  spark-master:
    <<: *airflow-common
    build:
      context: .
      dockerfile: ./docker/Dockerfile.spark
    container_name: spark-master
    user: "${AIRFLOW_UID:-50000}:0"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8083:8080"
      - "7077:7077"
    networks:
      - airflow
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/data/news_summary:/opt/airflow/data
      - ${AIRFLOW_PROJ_DIR:-.}/batch.env:/opt/airflow/.env:ro

  spark-worker:
    <<: *airflow-common
    build:
      context: .
      dockerfile: ./docker/Dockerfile.spark
    container_name: spark-worker
    user: "${AIRFLOW_UID:-50000}:0"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    networks:
      - airflow
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/airflow/data
      - ${AIRFLOW_PROJ_DIR:-.}/batch.env:/opt/airflow/.env:ro

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - airflow

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - airflow

  news-producer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.producer
    container_name: news-producer
    command: bash -c "python main.py"
    depends_on:
      kafka:
        condition: service_healthy
      postgres-news:
        condition: service_healthy
    networks:
      - airflow
    restart: on-failure
    volumes:
      - ./news-pipeline/producer:/opt/news-pipeline
      - ./logs/producer:/opt/news-pipeline/logs

  news-consumer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.consumer
    container_name: news-consumer
    user: root
    command: bash -c "python main.py"
    depends_on:
      kafka:
        condition: service_healthy
      postgres-news:
        condition: service_healthy
    networks:
      - airflow
    restart: on-failure
    volumes:
      - ./news-pipeline/consumer:/opt/news-pipeline
      - ./logs/consumer:/opt/news-pipeline/logs

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=elastic-docker-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2 
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2 
      - node.roles=master,data,ingest
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - TZ=Asia/Seoul
    ports:
      - "9200:9200"
    networks:
      - airflow
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=elastic-docker-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2 
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2 
      - node.roles=master,data,ingest
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - TZ=Asia/Seoul
    ports:
      - "9201:9200" 
    networks:
      - airflow
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9201/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
      - XPACK_ALERTING_ENABLED=false
      - XPACK_ACTIONS_ENABLED=false
      - XPACK_RULE_REGISTRY_WRITE_ENABLED=false
      - TELEMETRY_ENABLED=false
      - XPACK_SECURITY_SOLUTION_ENABLED=false
      - XPACK_INFRA_ENABLED=false
      - XPACK_LOGS_ENABLED=false
      - XPACK_ALERTING_ENABLED=false
      - XPACK_APM_ENABLED=false
      - XPACK_FLEET_ENABLED=false
      - XPACK_SECURITY_SOLUTION_ENABLED=false
      - XPACK_OBSERVABILITY_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_ML_ENABLED=false
      - TELEMETRY_ENABLED=false
      - MONITORING_ENABLED=false
    ports:
      - 5601:5601 
    networks:
      - airflow 

volumes:
  news-db-volume:

networks:
  airflow:
    driver: bridge
