FROM postgres:13

RUN apt-get update && apt-get install -y \
    postgresql-server-dev-13 \
    git \
    make \
    gcc \
    && git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git \
    && cd pgvector && make && make install

CMD ["postgres"]
