# Generated by Django 4.2.20 on 2025-05-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreadarticle",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.article"
            ),
        ),
    ]
