INSERT INTO news_article (title, writer, write_date, category, content, url, keywords)
VALUES
('총선 공약 발표, 청년 지원 확대', '홍길동', (CURRENT_DATE) + TIME '00:15', '정치',
 '여야가 청년 정책을 경쟁적으로 발표했다.', 'https://example.com/news/yd-0001',
 '["정치","청년","공약","정책"]'::jsonb),
('기준금리 동결…물가 안정 신호', '김민수', (CURRENT_DATE) + TIME '01:20', '경제',
 '한국은행이 기준금리를 동결하며 물가 흐름을 주시했다.', 'https://example.com/news/yd-0002',
 '["경제","금리","물가","통화정책"]'::jsonb),
('도심 역세권 개발 본격화', '이서연', (CURRENT_DATE) + TIME '02:05', '사회',
 '도심 재개발 사업이 속도를 내고 있다.', 'https://example.com/news/yd-0003',
 '["사회","부동산","재개발","도시계획"]'::jsonb),
('미국 증시 상승…빅테크 주도', '박지훈', (CURRENT_DATE) + TIME '03:40', '국제',
 '미 증시는 빅테크 호실적에 상승 마감.', 'https://example.com/news/yd-0004',
 '["국제","미국증시","나스닥","빅테크","주가"]'::jsonb),
('국내 팹리스, 차세대 AI 칩 공개', '정아름', (CURRENT_DATE) + TIME '04:10', 'IT/과학',
 '국내 팹리스가 경량 AI 가속기 칩을 선보였다.', 'https://example.com/news/yd-0005',
 '["IT","AI","반도체","칩","가속기"]'::jsonb),
('K리그 선두권 혼전, 주말 빅매치', '최운호', (CURRENT_DATE) + TIME '05:55', '스포츠',
 '상위권 팀들의 승점 차가 촘촘하다.', 'https://example.com/news/yd-0006',
 '["스포츠","축구","K리그","빅매치"]'::jsonb),
('새 전기차 보조금 개편안 윤곽', '김하늘', (CURRENT_DATE) + TIME '06:12', '경제',
 '전기차 보조금이 주행거리·효율 중심으로 재편된다.', 'https://example.com/news/yd-0007',
 '["경제","전기차","보조금","친환경"]'::jsonb),
('출근길 지하철 증편…혼잡 완화 기대', '유지수', (CURRENT_DATE) + TIME '07:30', '사회',
 '출근 시간대 열차가 증편된다.', 'https://example.com/news/yd-0008',
 '["사회","교통","지하철","혼잡"]'::jsonb),
('장마 후 첫 태풍 북상…주말 비상', '한도윤', (CURRENT_DATE) + TIME '08:45', '사회',
 '올해 첫 가을 태풍이 한반도에 접근한다.', 'https://example.com/news/yd-0009',
 '["날씨","태풍","기상청","호우"]'::jsonb),
('대규모 데이터센터 투자 발표', '오지훈', (CURRENT_DATE) + TIME '09:05', 'IT/과학',
 '클라우드 기업이 수도권에 데이터센터를 증설한다.', 'https://example.com/news/yd-0010',
 '["클라우드","데이터센터","AI","전력"]'::jsonb),
('문화재 야간개장, 시민 호응', '문소리', (CURRENT_DATE) + TIME '10:22', '문화',
 '사전예약이 조기 마감됐다.', 'https://example.com/news/yd-0011',
 '["문화","전시","야간개장","관광"]'::jsonb),
('대기업, 하반기 신입 공채 축소', '장유나', (CURRENT_DATE) + TIME '11:40', '경제',
 '글로벌 경기 둔화가 고용에도 영향.', 'https://example.com/news/yd-0012',
 '["경제","채용","고용","경기"]'::jsonb),
('국회, 데이터 활용법 개정 논의', '박상현', (CURRENT_DATE) + TIME '12:05', '정치',
 '가명정보 결합 절차 간소화 검토.', 'https://example.com/news/yd-0013',
 '["정치","데이터","개인정보","규제완화"]'::jsonb),
('원/달러 환율 하락…수출기업 한숨 돌려', '김도윤', (CURRENT_DATE) + TIME '13:15', '경제',
 '환율 안정세가 이어졌다.', 'https://example.com/news/yd-0014',
 '["환율","달러","수출","외환"]'::jsonb),
('메이저리그 코리안리거 멀티히트', '이준석', (CURRENT_DATE) + TIME '14:27', '스포츠',
 '타격감이 살아났다.', 'https://example.com/news/yd-0015',
 '["스포츠","야구","MLB","코리안리거"]'::jsonb),
('대형 플랫폼, 뉴스 저작권 협상 재개', '양수빈', (CURRENT_DATE) + TIME '15:00', 'IT/과학',
 '콘텐츠 사용료 산정이 쟁점.', 'https://example.com/news/yd-0016',
 '["플랫폼","저작권","뉴스","콘텐츠"]'::jsonb),
('세계 반도체 매출, 내년 역대 최대 전망', '정해인', (CURRENT_DATE) + TIME '16:18', '국제',
 'AI 수요가 성장을 견인.', 'https://example.com/news/yd-0017',
 '["국제","반도체","AI","매출"]'::jsonb),
('뮤직페스티벌 개막…도심 열기 후끈', '배지연', (CURRENT_DATE) + TIME '17:42', '문화',
 '메인 스테이지에 관객이 몰렸다.', 'https://example.com/news/yd-0018',
 '["문화","축제","공연","관광"]'::jsonb),
('부동산 거래 급증…전세 안정세', '오예진', (CURRENT_DATE) + TIME '18:05', '사회',
 '전세가율이 소폭 하락했다.', 'https://example.com/news/yd-0019',
 '["부동산","전세","거래","주택"]'::jsonb),
('스타트업, 생성형 AI로 업무 자동화', '노태현', (CURRENT_DATE) + TIME '19:20', 'IT/과학',
 '문서 요약과 질의응답을 자동화한다.', 'https://example.com/news/yd-0020',
 '["AI","생성형AI","자동화","업무효율"]'::jsonb),
('국제 유가 상승…인플레 우려 재점화', '서지수', (CURRENT_DATE) + TIME '20:10', '국제',
 '산유국 감산 이슈 재부각.', 'https://example.com/news/yd-0021',
 '["국제","유가","인플레이션","감산"]'::jsonb),
('프로야구 순위 요동…가을야구 안갯속', '성민재', (CURRENT_DATE) + TIME '21:33', '스포츠',
 '중위권 승부가 치열하다.', 'https://example.com/news/yd-0022',
 '["스포츠","야구","KBO","순위"]'::jsonb),
('도시 공원 리모델링…주민 만족 ↑', '남희진', (CURRENT_DATE) + TIME '22:08', '사회',
 '보행 동선과 휴식 공간이 개선됐다.', 'https://example.com/news/yd-0023',
 '["사회","도시","공원","리모델링"]'::jsonb),
('차세대 메모리 양산 준비 완료', '유가은', (CURRENT_DATE) + TIME '23:20', 'IT/과학',
 'HBM 신공정 도입이 임박했다.', 'https://example.com/news/yd-0024',
 '["반도체","HBM","공정","양산"]'::jsonb),
('AI 반도체 투자 러시', '김도경', (CURRENT_DATE) + TIME '09:55', 'IT/과학',
 '국내외 대규모 투자 소식이 잇따른다.', 'https://example.com/news/yd-0025',
 '["AI","반도체","투자","클라우드"]'::jsonb),
('금리 인하 기대감에 증시 상승', '박소민', (CURRENT_DATE) + TIME '11:05', '경제',
 '완화적 기조 전환 가능성이 거론된다.', 'https://example.com/news/yd-0026',
 '["금리","증시","완화","주가"]'::jsonb),
('태풍 북상에 항공편 일부 결항', '최나현', (CURRENT_DATE) + TIME '13:50', '사회',
 '공항 이용객은 운항 정보를 확인해야 한다.', 'https://example.com/news/yd-0027',
 '["태풍","항공","결항","날씨"]'::jsonb),
('전기차 배터리 리사이클링 확대', '이도현', (CURRENT_DATE) + TIME '15:40', '경제',
 '원재료 가격 절감에 도움이 될 전망.', 'https://example.com/news/yd-0028',
 '["전기차","배터리","리사이클링","원재료"]'::jsonb),
('부동산 규제 완화 논의 본격화', '방가영', (CURRENT_DATE) + TIME '16:55', '정치',
 '지역별 규제 차등 적용이 논의된다.', 'https://example.com/news/yd-0029',
 '["정치","부동산","규제완화","정책"]'::jsonb),
('클라우드 네이티브 전환 가속', '고인범', (CURRENT_DATE) + TIME '18:25', 'IT/과학',
 '레거시 시스템을 컨테이너 기반으로 전환.', 'https://example.com/news/yd-0030',
 '["클라우드","컨테이너","마이크로서비스","AI"]'::jsonb)
ON CONFLICT (url) DO NOTHING;
