# Generated by Django 4.2.20 on 2025-05-26 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import news.models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("writer", models.CharField(max_length=255)),
                ("write_date", models.DateTimeField()),
                ("category", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("url", models.URLField(unique=True)),
                ("keywords", news.models.SafeJSONField(default=list)),
                ("embedding", pgvector.django.vector.VectorField(null=True)),
                ("read", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "news_article",
            },
        ),
    ]
